version: '3'
services:
  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: keycloak
    command: ["-b", "0.0.0.0", "-Djboss.socket.binding.port-offset=1000"]
    #command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000","-Djboss.as.management.blocking.timeout=360000"]
    #volumes:
    #- ./realm-config:/opt/jboss/keycloak/realm-config
    #command: ["-b", "0.0.0.0", "-Djboss.socket.binding.port-offset=1000"]
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ETEC@2030
      DB_VENDOR: MYSQL
      DB_ADDR: 10.1.201.19
      DB_DATABASE: keycloak
      DB_USER: etec2021
      DB_PASSWORD: Etec@2030
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
    networks:
      - orchestra_default

volumes:
  keycloak-etec-volume:

networks:
  orchestra_default:
    external: true
