version: '3'
services:
  studio-app:
    image: ec2-204-236-204-108.compute-1.amazonaws.com:8085/fo-studio:etec
    container_name: studio
    ports:
      - "8085:80"
      - "8442:443"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
        reservations:
          cpus: '0.3'
          memory: 1024M
    networks:
      - orchestra_default

networks:
  orchestra_default:
    external: true

volumes:
  studio-volume:
