# Common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

keycloak-url: http://10.0.8.125:9080/auth/realms/etec/
security:
    oauth2:
        client:
            access-token-uri: ${keycloak-url}protocol/openid-connect/token
            user-authorization-uri: ${keycloak-url}protocol/openid-connect/auth
            scope: openid profile email
            client-secret: etec@2030-orchestra
        resource:
            user-info-uri: ${keycloak-url}protocol/openid-connect/userinfo
jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800

eureka:
    client:
        enabled: true
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@10.0.8.116:8761/eureka/

           
spring:
    liquibase:
        enabled: false
    datasource:
        password: Etec$2030
    cloud:
        config:
            fail-fast: false
        stream:
            kafka:
                binder:
                    brokers: 10.0.8.115
                    zk-nodes: 10.0.8.115
                    configuration.max.request.size: 2017767
feign:
   client:
       config:
           default:
               connectTimeout: 50000
               readTimeout: 50000
               loggerLevel: full
